import { useState } from 'react'
import { api } from '../utils/api'
import { Sparkles, ChevronDown, ChevronUp } from 'lucide-react'

export default function GenAIExplanation({ data }) {
  const [explanation, setExplanation] = useState(null)
  const [loading, setLoading]         = useState(false)
  const [expanded, setExpanded]       = useState(true)

  const generate = async () => {
    setLoading(true)
    try {
      const res = await api.explain(data)
      setExplanation(res.explanation)
    } finally { setLoading(false) }
  }

  return (
    <div className="card animate-fade-up" style={{animationDelay:'550ms',animationFillMode:'both',opacity:0}}>
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <div className="w-7 h-7 rounded-lg bg-accent/15 flex items-center justify-center">
            <Sparkles size={13} className="text-accent" />
          </div>
          <p className="section-label mb-0">AI Explanation</p>
        </div>
        {explanation && (
          <button onClick={() => setExpanded(e=>!e)} className="text-paper/30 hover:text-paper/60">
            {expanded ? <ChevronUp size={16}/> : <ChevronDown size={16}/>}
          </button>
        )}
      </div>

      {!explanation ? (
        <div className="flex flex-col items-center py-6 text-center">
          <p className="text-paper/30 text-sm font-body mb-4">
            Get a plain-language explanation of your current predictions from an AI model.
          </p>
          <button onClick={generate} disabled={loading}
            className="btn-primary flex items-center gap-2 text-sm disabled:opacity-50">
            {loading
              ? <><div className="w-3.5 h-3.5 border-2 border-white/30 border-t-white rounded-full animate-spin"/>Generating...</>
              : <><Sparkles size={13}/> Generate explanation</>}
          </button>
        </div>
      ) : expanded ? (
        <div>
          <p className="text-paper/70 font-body text-sm leading-relaxed">{explanation}</p>
          <div className="flex items-center justify-between mt-4">
            <p className="text-paper/20 text-xs font-mono">Generated by HuggingFace Mistral-7B</p>
            <button onClick={() => { setExplanation(null); generate() }}
              className="text-accent/60 hover:text-accent text-xs font-mono transition-colors">
              Regenerate
            </button>
          </div>
        </div>
      ) : null}
    </div>
  )
}
